apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv-volume-kiss
  labels:
    app: vizcolab
spec:
  capacity:
    storage: 15Gi
  local:
    path: /mnt/
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kiss
