apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-kiss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-storage
  volumeName: neo4j-pv-volume-kiss
